project:
  type: book
  output-dir: docs

filter: webr

book:
  title: "R code style with the `lintr` and `styler` packages"
  author: "Wesley Brooks"
  date: "`r Sys.Date()`"
  
  search: true
  repo-url: https://github.com/d-rug/workshop-lintr-styler
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_why-style-matters.qmd
    - 03_lintr.qmd
    - 04_styler.qmd
  
  sidebar:
    logo: https://github.com/d-rug/d-rug.github.io/raw/main/DRUG_final_cobalt.png
  site-url: https://d-rug.github.io

format:
  html:
    theme: cosmo
    number-sections: false